name: Release Go Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  buf-generate:
    name: Buf Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Buf
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.34.0/buf-$(uname -s)-$(uname -m)" -o buf
          chmod +x buf
          sudo mv buf /usr/local/bin/buf

      - name: Run buf generate
        run: |
          buf generate
          cp LICENSE gen/

      - name: Upload generated gen directory
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: gen/

  release:
    name: Create Release
    needs: buf-generate
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download generated gen directory
        uses: actions/download-artifact@v3
        with:
          name: generated-files
          path: gen
      # - name: Set up Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: "1.22" # Ensure Go version is consistent

      # - name: Initialize Go module
      #   run: |
      #     cp LICENSE gen/
      #     cd gen
      #     go mod init github.com/K-Kizuku/kotatuneko-proto/gen
      #     go mod tidy

      # - name: Test Go package
      #   run: |
      #     cd gen
      #     go test ./...

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "🏷️ release ${{ github.ref }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
