name: Buf Generate and Release

on:
  push:
    branches:
      - main

jobs:
  buf-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: Install buf
        run: |
          wget "https://github.com/bufbuild/buf/releases/download/v1.34.0/buf-$(uname -s)-$(uname -m)"
          chmod +x buf-Linux-x86_64
          sudo mv buf-Linux-x86_64 /usr/local/bin/buf

      - name: Generate code
        run: |
          buf generate

      - name: Commit generated code
        id: commit_generated_code
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🏷️ release $TAG_NAME"
          git push

      - name: Create Tag
        id: create_tag
        run: |
          git tag ${{ steps.commit_generated_code.outputs.TAG_NAME }}
          git push origin ${{ steps.commit_generated_code.outputs.TAG_NAME }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.commit_generated_code.outputs.TAG_NAME }}
          release_name: ${{ steps.commit_generated_code.outputs.TAG_NAME }}
          draft: false
          prerelease: false
