name: Release Go Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  buf-generate:
    name: Buf Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/download/v1.0.0-rc1/buf-Linux-x86_64 -o buf
          chmod +x buf
          sudo mv buf /usr/local/bin/buf

      - name: Run buf generate
        run: |
          buf generate

  test:
    name: Test
    needs: buf-generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test Go package
        run: |
          cd gen
          go test ./...

  release:
    name: Create Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23rc1" # Ensure Go version is consistent

      - name: Build Go package
        run: |
          cd gen
          go build ./...

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: "New release of the Go package."
